name: Build, Test, and Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with coverage
      run: coverage run -m unittest discover tests

    - name: Report coverage
      run: coverage report -m

    - name: Generate HTML coverage report
      run: coverage html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov

    - name: Verify coverage threshold
      run: coverage report --fail-under=80
      shell: bash
